### ISSUE TITLE
Equivalence of conv implementions

### ISSUE THREAD

**Issue by ToucheSir** [riveSunder/life_like#1]
Thanks for the blog post! If you wouldn't mind, I have a couple of comments/suggestions:

1. For PyTorch-like convolutions, the library to use is [NNlib](https://github.com/FluxML/NNlib.jl/) for an interface like `torch.nn.functional` or [Flux](https://github.com/FluxML/Flux.jl/) for one like `torch.nn`. These should be tuned for batched, multithreaded CPU + GPU workfloads. I would be surprised if an implementation using PyTorch's (I)FFT functionality could beat FFTW.jl, because the latter wraps an optimized C library!
2. The name "Julia" wasn't meant to be anthropromorphized. See https://stackoverflow.com/a/29292465 and [the FAQ](https://docs.julialang.org/en/v1/manual/faq/#Is-Julia-named-after-someone-or-something?) for more. So I think the language creators agree with you :)

**Comment by riveSunder** [comment]
Thanks for reading and for the tips and links. I've used Zygote in the past and I'd like to get more involved with the FluxML ecosystem, in particular for experiments with neural cellular automata. I've updated my performance tests and I'm going to be writing a follow-up in the next few days. 

What's new:
* I wrote a NumPy implementation that is much closer to what my Julia implementation is doing, namely using FFTs for convolutions. Unsurprisingly, Juilia is quite a bit faster, especially considering ...
* I noticed and fixed an issue in my Julia implementation that was performing two FFT convolutions for each update (and only using one of them). Fixing this makes the Julia implementation much faster, and it is now faster than the PyTorch implementation for small grid dimensions.
* I also upgraded the PyTorch version I am using to 1.9.0 from 1.5.1, so CARLE is faster now too. 

I'm not too worried about the name. I thought it was a little off-putting at first and now I'm happy to make fun of myself for overthinking it :)
